### ISSUE TITLE
Option to instantiate Linux::Cpuinfo with Str of `cat /proc/cpuinfo` output

### ISSUE THREAD

**Issue by markldevine** [jonathanstowe/p6-Linux-Cpuinfo#1]
I am creating classes that transport (SSH) information gathering commands (I.e. 'cat /proc/cpuinfo') to several systems concurrently.  I could have dozens of '/proc/cpuinfo' strings (UTF-8 in all my cases), and I'd like to use those strings to instantiate Linux::Cpuinfo objects.

I would greatly appreciate your efforts if you would provide an interface for this case.

(Also, thanks for being a clear source for consumers like me to glean how to build a dynamic Class!  I'll be mimicking that for years to come.)

**Comment by jonathanstowe** [comment]
That doesn't sound unreasonable - infact it probably supports that under the hood already but isn't properly exposed in the public interface.

I'll take a look when I get in :)

**Comment by jonathanstowe** [comment]
Hi,
I've exposed a ````cpu-info```` that can be supplied to the  constructor withe the data from a ```/proc/cpuinfo```` which will be used instead of the file.

Hope that helps.
